[build]
target = "riscv64gc-unknown-linux-gnu"
rustflags = ["-C", "target-feature=+crt-static"]

[target.riscv64gc-unknown-linux-gnu]
runner = "qemu-riscv64"
linker = "/opt/riscv/bin/riscv64-unknown-linux-gnu-gcc"
ar = "/opt/riscv/bin/riscv64-unknown-linux-ar"
# CI use other path